// Generated by scripts/generate-supabase-types.ps1
// Do not edit this file manually.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.1"
  }
  public: {
    Tables: {
      activity_events: {
        Row: {
          actor_user_id: string
          created_at: string | null
          id: string
          metadata: Json | null
          read_at: number | null
          story_id: string
          synced_at: number | null
          target_user_id: string
          type: string
        }
        Insert: {
          actor_user_id: string
          created_at?: string | null
          id?: string
          metadata?: Json | null
          read_at?: number | null
          story_id: string
          synced_at?: number | null
          target_user_id: string
          type: string
        }
        Update: {
          actor_user_id?: string
          created_at?: string | null
          id?: string
          metadata?: Json | null
          read_at?: number | null
          story_id?: string
          synced_at?: number | null
          target_user_id?: string
          type?: string
        }
        Relationships: [
          {
            foreignKeyName: "activity_events_story_id_fkey"
            columns: ["story_id"]
            isOneToOne: false
            referencedRelation: "audio_recordings"
            referencedColumns: ["id"]
          },
        ]
      }
      audio_recordings: {
        Row: {
          created_at: string | null
          deleted_at: string | null
          duration_ms: number | null
          file_path: string
          id: string
          is_favorite: boolean | null
          is_soft_deleted: boolean | null
          sync_status: string | null
          title: string | null
          topic_id: string | null
          transcode_status: string | null
          transcription: string | null
          unlock_at: number | null
          upload_format: string | null
          upload_path: string | null
          user_id: string
        }
        Insert: {
          created_at?: string | null
          deleted_at?: string | null
          duration_ms?: number | null
          file_path: string
          id?: string
          is_favorite?: boolean | null
          is_soft_deleted?: boolean | null
          sync_status?: string | null
          title?: string | null
          topic_id?: string | null
          transcode_status?: string | null
          transcription?: string | null
          unlock_at?: number | null
          upload_format?: string | null
          upload_path?: string | null
          user_id: string
        }
        Update: {
          created_at?: string | null
          deleted_at?: string | null
          duration_ms?: number | null
          file_path?: string
          id?: string
          is_favorite?: boolean | null
          is_soft_deleted?: boolean | null
          sync_status?: string | null
          title?: string | null
          topic_id?: string | null
          transcode_status?: string | null
          transcription?: string | null
          unlock_at?: number | null
          upload_format?: string | null
          upload_path?: string | null
          user_id?: string
        }
        Relationships: []
      }
      bonding_requests: {
        Row: {
          created_at: string | null
          id: string
          sender_id: string
          status: string
          target_id: string
          updated_at: string | null
        }
        Insert: {
          created_at?: string | null
          id?: string
          sender_id: string
          status: string
          target_id: string
          updated_at?: string | null
        }
        Update: {
          created_at?: string | null
          id?: string
          sender_id?: string
          status?: string
          target_id?: string
          updated_at?: string | null
        }
        Relationships: []
      }
      device_codes: {
        Row: {
          code: string
          created_at: string
          expires_at: string
          family_user_id: string
          id: string
          revoked_at: string | null
          used_at: string | null
        }
        Insert: {
          code: string
          created_at?: string
          expires_at: string
          family_user_id: string
          id?: string
          revoked_at?: string | null
          used_at?: string | null
        }
        Update: {
          code?: string
          created_at?: string
          expires_at?: string
          family_user_id?: string
          id?: string
          revoked_at?: string | null
          used_at?: string | null
        }
        Relationships: []
      }
      devices: {
        Row: {
          created_at: string
          device_name: string | null
          family_user_id: string
          id: string
          last_seen_at: string | null
          revoked_at: string | null
        }
        Insert: {
          created_at?: string
          device_name?: string | null
          family_user_id: string
          id?: string
          last_seen_at?: string | null
          revoked_at?: string | null
        }
        Update: {
          created_at?: string
          device_name?: string | null
          family_user_id?: string
          id?: string
          last_seen_at?: string | null
          revoked_at?: string | null
        }
        Relationships: []
      }
      discovery_questions: {
        Row: {
          category: string
          created_at: string | null
          id: string
          priority: number | null
          question_text: string
          tags: string[] | null
          updated_at: string | null
        }
        Insert: {
          category: string
          created_at?: string | null
          id?: string
          priority?: number | null
          question_text: string
          tags?: string[] | null
          updated_at?: string | null
        }
        Update: {
          category?: string
          created_at?: string | null
          id?: string
          priority?: number | null
          question_text?: string
          tags?: string[] | null
          updated_at?: string | null
        }
        Relationships: []
      }
      family_connections: {
        Row: {
          created_at: string | null
          id: string
          member_id: string
          senior_id: string
        }
        Insert: {
          created_at?: string | null
          id?: string
          member_id: string
          senior_id: string
        }
        Update: {
          created_at?: string | null
          id?: string
          member_id?: string
          senior_id?: string
        }
        Relationships: []
      }
      family_members: {
        Row: {
          accepted_at: string | null
          email: string
          family_id: string
          id: string
          invite_token: string | null
          invited_at: string
          invited_by: string | null
          role: string
          status: string
          user_id: string | null
        }
        Insert: {
          accepted_at?: string | null
          email: string
          family_id: string
          id?: string
          invite_token?: string | null
          invited_at?: string
          invited_by?: string | null
          role?: string
          status?: string
          user_id?: string | null
        }
        Update: {
          accepted_at?: string | null
          email?: string
          family_id?: string
          id?: string
          invite_token?: string | null
          invited_at?: string
          invited_by?: string | null
          role?: string
          status?: string
          user_id?: string | null
        }
        Relationships: []
      }
      family_questions: {
        Row: {
          answered_at: string | null
          category: string
          created_at: string | null
          family_user_id: string
          id: string
          question_text: string
          recording_id: string | null
          senior_user_id: string
        }
        Insert: {
          answered_at?: string | null
          category?: string
          created_at?: string | null
          family_user_id: string
          id?: string
          question_text: string
          recording_id?: string | null
          senior_user_id: string
        }
        Update: {
          answered_at?: string | null
          category?: string
          created_at?: string | null
          family_user_id?: string
          id?: string
          question_text?: string
          recording_id?: string | null
          senior_user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "family_questions_recording_id_fkey"
            columns: ["recording_id"]
            isOneToOne: false
            referencedRelation: "audio_recordings"
            referencedColumns: ["id"]
          },
        ]
      }
      notification_queue: {
        Row: {
          created_at: string | null
          delivered_at: string | null
          event_id: string
          event_type: string
          grouped_with: string[] | null
          id: string
          scheduled_for: string
          user_id: string
        }
        Insert: {
          created_at?: string | null
          delivered_at?: string | null
          event_id: string
          event_type: string
          grouped_with?: string[] | null
          id?: string
          scheduled_for: string
          user_id: string
        }
        Update: {
          created_at?: string | null
          delivered_at?: string | null
          event_id?: string
          event_type?: string
          grouped_with?: string[] | null
          id?: string
          scheduled_for?: string
          user_id?: string
        }
        Relationships: []
      }
      profiles: {
        Row: {
          avatar_uri: string | null
          avatar_url: string | null
          bio: string | null
          birth_date: string | null
          created_at: string | null
          display_name: string | null
          email: string | null
          font_scale_index: number | null
          full_name: string | null
          id: string
          is_anonymous: boolean | null
          language: string | null
          role: string | null
          updated_at: string | null
          upgraded_at: string | null
          user_id: string | null
        }
        Insert: {
          avatar_uri?: string | null
          avatar_url?: string | null
          bio?: string | null
          birth_date?: string | null
          created_at?: string | null
          display_name?: string | null
          email?: string | null
          font_scale_index?: number | null
          full_name?: string | null
          id: string
          is_anonymous?: boolean | null
          language?: string | null
          role?: string | null
          updated_at?: string | null
          upgraded_at?: string | null
          user_id?: string | null
        }
        Update: {
          avatar_uri?: string | null
          avatar_url?: string | null
          bio?: string | null
          birth_date?: string | null
          created_at?: string | null
          display_name?: string | null
          email?: string | null
          font_scale_index?: number | null
          full_name?: string | null
          id?: string
          is_anonymous?: boolean | null
          language?: string | null
          role?: string | null
          updated_at?: string | null
          upgraded_at?: string | null
          user_id?: string | null
        }
        Relationships: []
      }
      recovery_codes: {
        Row: {
          code: string
          created_at: string | null
          expires_at: string | null
          id: string
          is_active: boolean | null
          revoked_at: string | null
          user_id: string
        }
        Insert: {
          code: string
          created_at?: string | null
          expires_at?: string | null
          id?: string
          is_active?: boolean | null
          revoked_at?: string | null
          user_id: string
        }
        Update: {
          code?: string
          created_at?: string | null
          expires_at?: string | null
          id?: string
          is_active?: boolean | null
          revoked_at?: string | null
          user_id?: string
        }
        Relationships: []
      }
      story_comments: {
        Row: {
          content: string
          created_at: string | null
          id: string
          story_id: string
          updated_at: string | null
          user_id: string
        }
        Insert: {
          content: string
          created_at?: string | null
          id?: string
          story_id: string
          updated_at?: string | null
          user_id: string
        }
        Update: {
          content?: string
          created_at?: string | null
          id?: string
          story_id?: string
          updated_at?: string | null
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "story_comments_story_id_fkey"
            columns: ["story_id"]
            isOneToOne: false
            referencedRelation: "audio_recordings"
            referencedColumns: ["id"]
          },
        ]
      }
      story_reactions: {
        Row: {
          created_at: string | null
          id: string
          reaction_type: string
          story_id: string
          user_id: string
        }
        Insert: {
          created_at?: string | null
          id?: string
          reaction_type: string
          story_id: string
          user_id: string
        }
        Update: {
          created_at?: string | null
          id?: string
          reaction_type?: string
          story_id?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "story_reactions_story_id_fkey"
            columns: ["story_id"]
            isOneToOne: false
            referencedRelation: "audio_recordings"
            referencedColumns: ["id"]
          },
        ]
      }
      user_notification_settings: {
        Row: {
          notifications_enabled: boolean | null
          quiet_hours_end: string | null
          quiet_hours_start: string | null
          time_zone: string | null
          updated_at: string | null
          user_id: string
        }
        Insert: {
          notifications_enabled?: boolean | null
          quiet_hours_end?: string | null
          quiet_hours_start?: string | null
          time_zone?: string | null
          updated_at?: string | null
          user_id: string
        }
        Update: {
          notifications_enabled?: boolean | null
          quiet_hours_end?: string | null
          quiet_hours_start?: string | null
          time_zone?: string | null
          updated_at?: string | null
          user_id?: string
        }
        Relationships: []
      }
      user_push_tokens: {
        Row: {
          created_at: string | null
          device_type: string
          id: string
          push_token: string
          updated_at: string | null
          user_id: string
        }
        Insert: {
          created_at?: string | null
          device_type: string
          id?: string
          push_token: string
          updated_at?: string | null
          user_id: string
        }
        Update: {
          created_at?: string | null
          device_type?: string
          id?: string
          push_token?: string
          updated_at?: string | null
          user_id?: string
        }
        Relationships: []
      }
      user_settings: {
        Row: {
          cloud_ai_enabled: boolean | null
          created_at: string | null
          updated_at: string | null
          user_id: string
        }
        Insert: {
          cloud_ai_enabled?: boolean | null
          created_at?: string | null
          updated_at?: string | null
          user_id: string
        }
        Update: {
          cloud_ai_enabled?: boolean | null
          created_at?: string | null
          updated_at?: string | null
          user_id?: string
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      accept_family_invite: { Args: { p_token: string }; Returns: undefined }
      cleanup_abandoned_anonymous_accounts: { Args: never; Returns: undefined }
      create_family_invite: {
        Args: { p_email: string }
        Returns: {
          invite_token: string
        }[]
      }
      generate_device_code: {
        Args: never
        Returns: {
          code: string
          expires_at: string
        }[]
      }
      generate_senior_recovery_code: {
        Args: { p_senior_id: string }
        Returns: {
          display_code: string
          expires_at: string
        }[]
      }
      get_family_members: {
        Args: never
        Returns: {
          avatar_url: string
          display_name: string
          email: string
          linked_at: string
          role: string
          user_id: string
        }[]
      }
      is_user_anonymous: { Args: never; Returns: boolean }
      list_family_devices: {
        Args: never
        Returns: {
          created_at: string
          device_name: string
          id: string
          last_seen_at: string
          revoked_at: string
        }[]
      }
      remove_family_member: {
        Args: { p_target_user_id: string }
        Returns: undefined
      }
      resolve_activity_actor_name: {
        Args: { p_user_id: string }
        Returns: string
      }
      respond_to_bonding_request: {
        Args: { new_status: string; request_id: string }
        Returns: undefined
      }
      revoke_device: { Args: { p_device_id: string }; Returns: undefined }
      validate_recovery_code: {
        Args: { p_code: string }
        Returns: {
          expires_at: string
          is_valid: boolean
          user_id: string
        }[]
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {},
  },
} as const

